### ISSUE TITLE
Add playground as a release for easier access on mobile

### ISSUE THREAD

**Issue by yourlocaltechboi** [TheIntelCorei9/Swift-Student-Challenge#1]
Hello! I just wanted to suggest adding the playground file to a release, so mobile users can easily download the playground. Even just making a release will make a .zip of the repo, and it would make the project more accessible. Thanks!

**Comment by david-mazzeo** [comment]
Great idea, I’ll push it within a few hours, thanks! 😊

**Comment by david-mazzeo** [comment]
Just did it, it's now available as the v1.0sp (sp = Swift Playground) release!
